name: Link checker

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Check links
      #FIXME Need to allow duplicates (same links on the same page)
      run: |
        gem install awesome_bot
        awesome_bot --white-list https://gitlab-sim.informatik.uni-stuttgart.de/  --allow-ssl --allow-redirect --allow-dupe $(find . -iname "*.md" -type f)
